### ISSUE TITLE
libopus 1.3.1 does not compile

### ISSUE THREAD

**Issue by Bhaal22** [KallistiOS/kos-ports#8] opened 2020-06-02 22:03 UTC
My dc environment:

```
KOS_STRIP=/opt/toolchains/dc/sh-elf/bin/sh-elf-strip
DC_ARM_AFLAGS=-mcpu=arm7di --fix-v4bx
KOS_AFLAGS= -little
KOS_CCPLUS=/opt/toolchains/dc/sh-elf/bin/sh-elf-g++
HOSTNAME=33353e70e801
DC_ARM_AS=/opt/toolchains/dc/arm-eabi/bin/arm-eabi-as
DC_ARM_AR=/opt/toolchains/dc/arm-eabi/bin/arm-eabi-ar
KOS_GENROMFS=/src/dc/kos/utils/genromfs/genromfs
KOS_PORTS=/src/dc/kos/../kos-ports
KOS_LOADER=dc-tool -x
KOS_OBJCOPY=/opt/toolchains/dc/sh-elf/bin/sh-elf-objcopy
KOS_LIB_PATHS=-L/src/dc/kos/lib/dreamcast -L/src/dc/kos/addons/lib/dreamcast -L/src/dc/kos/../kos-ports/lib
KOS_CFLAGS=-O2 -fomit-frame-pointer -ml -m4-single-only -ffunction-sections -fdata-sections -I/src/dc/kos/../kos-ports/include -I/src/dc/kos/include -I/src/dc/kos/kernel/arch/dreamcast/include -I/src/dc/kos/addons/include -I/src/dc/kos/../kos-ports/include -D_arch_dreamcast -D_arch_sub_pristine -Wall -g -fno-builtin
PWD=/src/project
KOS_GCCVER=9.3.0
KOS_ARCH=dreamcast
KOS_LD_SCRIPT=-T/src/dc/kos/utils/ldscripts/shlelf.xc
KOS_LIBS=-Wl,--start-group -lkallisti -lc -lgcc -Wl,--end-group
HOME=/root
KOS_SUBARCH=pristine
KOS_LD=/opt/toolchains/dc/sh-elf/bin/sh-elf-ld
KOS_BASE=/src/dc/kos
KOS_CPPSTD=-std=gnu++98
KOS_AR=/opt/toolchains/dc/sh-elf/bin/sh-elf-ar
KOS_AS=/opt/toolchains/dc/sh-elf/bin/sh-elf-as
KOS_CC=/opt/toolchains/dc/sh-elf/bin/sh-elf-gcc
EXTRA_MAKEFILE_BASE=/usr/local/dc
KOS_INC_PATHS=-I/src/dc/kos/../kos-ports/include -I/src/dc/kos/include -I/src/dc/kos/kernel/arch/dreamcast/include -I/src/dc/kos/addons/include -I/src/dc/kos/../kos-ports/include
TERM=xterm
KOS_LDFLAGS= -ml -m4-single-only -Wl,-Ttext=0x8c010000 -Wl,--gc-sections -T/src/dc/kos/utils/ldscripts/shlelf.xc -nodefaultlibs -L/src/dc/kos/lib/dreamcast -L/src/dc/kos/addons/lib/dreamcast -L/src/dc/kos/../kos-ports/lib
DC_ARM_OBJCOPY=/opt/toolchains/dc/arm-eabi/bin/arm-eabi-objcopy
SHLVL=1
KOS_MAKE=make
DC_ARM_CC=/opt/toolchains/dc/arm-eabi/bin/arm-eabi-gcc
KOS_START=
KOS_CC_PREFIX=sh-elf
KOS_ARCH_DIR=/src/dc/kos/kernel/arch/dreamcast
DC_ARM_LD=/opt/toolchains/dc/arm-eabi/bin/arm-eabi-ld
PATH=/opt/toolchains/dc/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/toolchains/dc/sh-elf/bin:/src/dc/kos/utils/gnu_wrappers
DC_ARM_CFLAGS=-mcpu=arm7di -Wall -O2 -fno-strict-aliasing -Wl,--fix-v4bx -Wa,--fix-v4bx
KOS_CPPFLAGS=  -fno-operator-names -fno-rtti -fno-exceptions
KOS_CSTD=-std=c99
DC_ARM_BASE=/opt/toolchains/dc/arm-eabi
KOS_RANLIB=/opt/toolchains/dc/sh-elf/bin/sh-elf-ranlib
KOS_CC_BASE=/opt/toolchains/dc/sh-elf
DC_ARM_PREFIX=arm-eabi
```

```
root@33353e70e801:/src/project# sh-elf-gcc -v
Using built-in specs.
COLLECT_GCC=sh-elf-gcc
COLLECT_LTO_WRAPPER=/opt/toolchains/dc/sh-elf/libexec/gcc/sh-elf/9.3.0/lto-wrapper
Target: sh-elf
Configured with: ../gcc-9.3.0/configure --target=sh-elf --prefix=/opt/toolchains/dc/sh-elf --without-headers --with-newlib --enable-languages=c --disable-libssp --disable-tls --with-multilib-list=m4-single-only --with-endian=little --with-cpu=m4-single-only CXX=g++ : (reconfigured) ../gcc-9.3.0/configure --target=sh-elf --prefix=/opt/toolchains/dc/sh-elf --with-newlib --disable-libssp --disable-tls --enable-threads=kos --enable-languages=c,c++,objc,obj-c++ --with-multilib-list=m4-single-only --with-endian=little --with-cpu=m4-single-only CXX=g++
Thread model: kos
gcc version 9.3.0 (GCC)
```

Compilation of libopus:

```
root@33353e70e801:/src/project# make
make  all-recursive
make[1]: Entering directory '/src/project'
make[2]: Entering directory '/src/project'
  CC       celt/bands.lo
In file included from /opt/toolchains/dc/sh-elf/sh-elf/include/stdio.h:800,
                 from celt/os_support.h:42,
                 from celt/bands.c:40:
/opt/toolchains/dc/sh-elf/sh-elf/include/ssp/stdio.h:40:5: error: unknown type name '__va_list'; did you mean 'va_list'?
   40 |     __va_list)
      |     ^~~~~~~~~
      |     va_list
/opt/toolchains/dc/sh-elf/sh-elf/include/ssp/stdio.h:46:30: error: unknown type name '__va_list'; did you mean 'va_list'?
   46 |      const char *__restrict, __va_list)
```

**Comment by ljsebald** [comment] 2020-06-02 22:14
Duplicate of #7. 

Update KallistiOS itself and the issue will be resolved.

**Closed by ljsebald** 2020-06-02 22:14 UTC

**Comment by Bhaal22** [comment] 2020-06-02 22:25
ok cool. found your commit.

https://github.com/KallistiOS/KallistiOS/commit/b3967a49ba45219759a9b28a884b9093a46927f4

tks.
